import { createAction } from 'redux-starter-kit';

export const USERS_RECEIVED = 'USERS_RECEIVED';
export const USERS_ERROR = 'USERS_ERROR';
export const USER_UPDATE = 'USER_UPDATE';
export const USERROLES_RECEIVED = 'USERROLES_RECEIVED';
export const USERROLES_ERROR = 'USERROLES_ERROR';
export const PASSWORDS_UPDATE = 'PASSWORDS_UPDATE';
export const ROLES_RECEIVED = 'ROLES_RECEIVED';
export const ROLES_ERROR = 'ROLES_ERROR';
export const ROLE_UPDATE = 'ROLE_UPDATE';
export const ROLEPERMISSIONS_RECEIVED = 'ROLEPERMISSIONS_RECEIVED';
export const ROLEPERMISSIONS_ERROR = 'ROLEPERMISSIONS_ERROR';
export const PERMISSIONS_RECEIVED = 'PERMISSIONS_RECEIVED';
export const PERMISSIONS_ERROR = 'PERMISSIONS_ERROR';
export const PERMISSION_UPDATE = 'PERMISSION_UPDATE';
export const FORMFIELD_UPDATE = 'FORMFIELD_UPDATE';
